
stages:
- stage: website
  variables:
  - template: variables/dev.yml
  displayName: Website
  jobs:
  - job: Website
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'UselessProject'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "${{variables.website}}\$web/useless.png"
            sudo apt install graphviz
            python -m pip install diagrams
            python diagram.py
              export AZCOPY_SPA_CLIENT_SECRET="$servicePrincipalKey"
              azcopy login --service-principal --application-id $servicePrincipalId --tenant-id $tenantId
              azcopy cp "useless.png" \
              "${{variables.website}}\$web/useless.png"
          addSpnToEnvironment: true


