

stages:
- stage: Terraform
  displayName: Terraform Steps
  variables:
  - template: variables/dev.yml
  jobs:
  - job: Apply
    steps:
      - task: AzureCLI@2
        displayName: Terraform Init
        inputs:
          workingDirectory: ${{variables.workingdir}}
          azureSubscription: 'UselessProject'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
              export ARM_CLIENT_ID="$servicePrincipalId"
              export ARM_CLIENT_SECRET="$servicePrincipalKey"
              export ARM_SUBSCRIPTION_ID=${{variables.subid}}
              export ARM_TENANT_ID="$tenantId"
              terraform init --backend-config=backend.conf
          addSpnToEnvironment: true
      - task: AzureCLI@2
        displayName: Terraform Plan
        inputs:
          workingDirectory: ${{variables.workingdir}}
          azureSubscription: 'UselessProject'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
              export ARM_CLIENT_ID="$servicePrincipalId"
              export ARM_CLIENT_SECRET="$servicePrincipalKey"
              export ARM_SUBSCRIPTION_ID=${{variables.subid}}
              export ARM_TENANT_ID="$tenantId"
              terraform plan
          addSpnToEnvironment: true
      - task: AzureCLI@2
        displayName: Terraform Apply
        inputs:
          workingDirectory: ${{variables.workingdir}}
          azureSubscription: 'UselessProject'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
              export ARM_CLIENT_ID="$servicePrincipalId"
              export ARM_CLIENT_SECRET="$servicePrincipalKey"
              export ARM_SUBSCRIPTION_ID=${{variables.subid}}
              export ARM_TENANT_ID="$tenantId"
              terraform apply --auto-approve
          addSpnToEnvironment: true

